// AUTO-GENERATED by scripts/update-codex-protocol.mjs. Do not edit.
export const CODEX_PROTOCOL_BASELINE = {
  codexVersion: "0.151.0",
  stableSchemaHash:
    "sha256:fe72700cd987211a7e7c371a26798ea191b2036b840502ddb4439069d5dd353a",
  experimentalSchemaHash:
    "sha256:a8d8a066997eaad3e74c493aa69e9d0cba89c6229dc01ba9fd6b2f200ac65938",
} as const;
